version: '3.8'
services:
  rasa:
    container_name: crp_chatbot
    image: rasa/rasa:3.6.20-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
      - --enable-api
      - --cors
      - "*"
